# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: DESKTOP-1T973CK

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: UiPathInstallPlatform@4
  inputs:
    cliVersion: 'WIN_23.10.8894.39673'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Training Demo'
    packagesPath: '$(Build.ArtifactStagingDirectory)'
    folderName: 'Test'
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.ArtifactStagingDirectory)'
    orchestratorConnection: 'Training Demo'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
    traceLevel: 'Verbose'